# Generated by Django 3.1.4 on 2020-12-16 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('column_separator', models.CharField(choices=[('COM', 'Comma'), ('DOT', 'Dot'), ('COL', 'Colon')], default='COM', max_length=3)),
                ('string_character', models.CharField(choices=[('QU', 'Quote'), ('DQ', 'Double-quote')], default='DQ', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PR', 'Progressing'), ('RD', 'Ready')], default='PR', max_length=3)),
                ('file', models.FileField(blank=True, null=True, upload_to='data_sets/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataschema_app.dataschema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('FLN', 'Full name'), ('JOB', 'Job'), ('INT', 'Integer'), ('TXT', 'Text'), ('DAT', 'Date')], max_length=3)),
                ('order', models.PositiveSmallIntegerField()),
                ('range_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('range_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataschema_app.dataschema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
